# Checks scripts.
name: scripts
on:
  pull_request:
  push:
permissions: read-all
jobs:
  run_scripts_freebsd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Generate test data
      id: build_freebsd
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        mem: 4096
        # Note that the test scripts require bash
        prepare: |
          pkg install -y bash freebsd-bsdlabel
        run: |
          ./generate-specimens-bsd.sh
    - uses: actions/upload-artifact@v7
      with:
        name: specimens-freebsd
        path: specimens/newfs/*.raw
